name: djepe
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  dropdown_button2: ^1.9.2
  equatable: ^2.0.5
  get_storage: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_map: ^3.1.0
  flutter_svg: ^2.0.0+1
  searchable_listview: ^1.7.2
  font_awesome_flutter: ^10.3.0
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  intl: any
  intl_phone_number_input: ^0.7.2
  latlong2: ^0.8.1
  location: ^4.4.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/
    - assets/icons/
    - assets/icons/svg/
